baseURL = "https://example.com/"
languageCode = "en-us"
title = "Origami Views"
enableRobotsTXT = true

[pagination]
  pagerSize = 10

[params]
  description = "Folded perspectives on anime"
  author = "Origami Views Team"

[outputs]
  home = ["HTML", "RSS"]

[sitemap]
  changefreq = "daily"
  priority = 0.8

[markup.goldmark.renderer]
  unsafe = true
